simplify debian config files

diff --git a/debian/wmbeacons.init b/debian/wmbeacons.init
--- a/debian/wmbeacons.init
+++ b/debian/wmbeacons.init
@@ -10,20 +10,23 @@
 # Description:       Start and stop wmbeacons web application.
 ### END INIT INFO
 
-PACKAGE=wmbeacons
+PACKAGE=`basename $0`
 PIDFILE=/var/run/$PACKAGE.pid
-CARTON=/usr/local/bin/carton
-PORT=6019
+
+[ -f /etc/default/$PACKAGE ] && . /etc/default/$PACKAGE
 
 start () {
-    [ -x $CARTON ] || exit 5
-    cd /srv/$PACKAGE
     echo -n "Starting $0: "
+    if [ -z "$PORT" -o -z "$WORKERS" ]; then
+        echo "missing configuration PORT and/or WORKERS"
+        exit 5
+    fi
+    cd /srv/$PACKAGE
     carton exec starman --pid $PIDFILE --daemonize \
-        --workers 5 --port $PORT --user wmbeacons \
+        --workers $WORKERS --port $PORT --user $PACKAGE \
         --error-log /var/log/$PACKAGE/error.log \
         --access-log /var/log/$PACKAGE/access.log \
-        /srv/wmbeacons/bin/app.psgi        # 2>&1 > /dev/null
+        /srv/$PACKAGE/bin/app.psgi
     retval=$?
     if [ $retval -eq 0 ]; then
         echo "done"
